### ISSUE TITLE
Add swipe navigation on map items

### ISSUE THREAD

**Issue by darowsluk** [GrupaMedialnaSalwator/kompas.sds#126]
As a user
I want to swipe down on the map item to close it

**Requirements:**
- Implement modal bottom sheet for the map item view
- Add curved corners to image
- Add gradient to background color

**Comment by darowsluk** [comment]
Resource for dragable modal bottom sheet: https://www.youtube.com/watch?v=AjAQglJKcb4

**Comment by knutm92** [comment]
@darowsluk Just came across a cool blur effect that I thought might be interesting as a layer on top of the map background.  Here's a link in case you'd like to test it out https://www.youtube.com/watch?v=WxP9ABzfgow

**Comment by darowsluk** [comment]
@knutm92 Thanks for the link. I tried around different looks, but it seems to me that the gradient background works the best since the blurred map looks unfinished.

**Comment by darowsluk** [comment]
fixed #126
