### ISSUE TITLE
Set New Name

### ISSUE THREAD

**Issue by darowsluk** [GrupaMedialnaSalwator/kompas.sds#14]
As developer
I want to have a good name for the project.

**Requirements:**
Change project name in:
1. GitHub
2. Flutter project
3. Firebase

**Comment by knutm92** [comment]
To open the name discussion I'll share a few ideas that came to my mind:

Salwatoriański Kompas / Salvatorian Compass
kompas.sds / compass.sds
Kompas SDS / Compass SDS
odkryj.sds / discover.sds

Play Store guidelines
https://android-developers.googleblog.com/2021/04/updated-guidance-to-improve-your-app.html
Apple Store guidelines
https://developer.apple.com/app-store/review/guidelines/

**Comment by darowsluk** [comment]
Adding to the suggestion list:

- viator.sds (latin for "traveler")
- ecce.sds (latin for "behold, see, look")
- visus.sds (latin for "to look at")
- miratus.sds (latin for "to be amazed")
